deployName: podinfo-operator
podinfo-operator:
  image: docker.io/patjones/podinfo-operator:240317-150819-main-521beb7
  replicas: "2"
  controller:
    resources:
      memoryLimit: '64Mi'
      cpuRequest: '100m'

