apiVersion: my.api.group.patjones.io/v1beta1
kind: MyAppResource
metadata:
  name: whatever
  namespace: whatever
spec:
  replicaCount: 2
  resources:
    memoryLimit: 64Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "#34ebd8"
    message: "hullo"
  redis:
    enabled: false
