apiVersion: my.api.group.my.domain/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: podinfo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: podinfo-operator
  name: myappresource-sample
spec:
  # TODO(user): Add fields here
